// <auto-generated />
namespace WebRole1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NullablePiSpyDeviceIdForCreatingGroups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullablePiSpyDeviceIdForCreatingGroups));
        
        string IMigrationMetadata.Id
        {
            get { return "201510041902477_NullablePiSpyDeviceIdForCreatingGroups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
